[versions]
agp = "8.13.0"
ksp = "2.2.21-2.0.4"
kotlin = "2.2.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
composeBom = "2025.12.01"
appcompat = "1.7.1"
hiltAndroid = "2.57.2"
hiltNavigationCompose = "1.3.0"
firebaseBom = "34.7.0"
firebaseMessaging = "25.0.1"
googleServices = "4.4.4"
playServicesAds = "24.9.0"
appUpdateVersion = "2.1.0"
retrofit = "3.0.0"
oauthVersion = "1.41.0"
coil = "2.7.0"
navigationCompose = "2.9.6"
kotlinxSerializationVersion = "1.9.0"
truth = "1.4.5"
coreTest = "2.2.0"
hiltTest = "2.57.2"
testRunner = "1.7.0"
mockito = "1.14.7"

[libraries]
# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-realtime-database = { module = "com.google.firebase:firebase-database" }
firebase-storage = { module = "com.google.firebase:firebase-storage" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
# Admob
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
# InApp Update
app-update = { module = "com.google.android.play:app-update", version.ref = "appUpdateVersion" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdateVersion" }
# Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
gson-converter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
# OAuth
google-oauth = { module = "com.google.auth:google-auth-library-oauth2-http", version.ref = "oauthVersion" }
# Coil
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
# Navigation
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
# Serialization
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationVersion" }
# Truth
google-truth = { module = "com.google.truth:truth", version.ref = "truth" }
# Test Core
core-test = { module = "androidx.arch.core:core-testing", version.ref = "coreTest" }
# Hilt Test
hilt-test = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltTest" }
# Test Runner
test-runner = { module = "androidx.test:runner", version.ref = "testRunner" }
# Mockito
mockito = { module = "io.mockk:mockk", version.ref = "mockito" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid"}
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }